// #include <../exception.dpl>

fn factorial(n: int): int {
	if (n < 0) {
		return -1; // TODO: raise an exception
	}

	if (n == 0 || n == 1) {
		return 1;
	}

	let result: int = 1;
	let i: int;
	for (i = 2; i <= n; i += 1) {
		result *= i;
	}
	return result;
}